version: '3.8'
services:
  web:
    image: crewai-video:latest
    build: .
    env_file: .env
    ports:
      - "80:8080"
    depends_on:
      - redis
      - minio

  worker:
    image: crewai-video:latest
    command: ["python", "worker.py"]   # starts Celery worker
    env_file: .env
    depends_on:
      - redis
      - minio

  redis:
    image: redis:7-alpine
    restart: always

  minio:
    image: minio/minio:latest
    command: server /data
    environment:
      MINIO_ROOT_USER: miniouser
      MINIO_ROOT_PASSWORD: miniosecret
    ports:
      - "9000:9000"
    volumes:
      - minio_data:/data

volumes:
  minio_data:
